import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollContainer: {
    alignItems: 'center',
    paddingBottom: 30,
  },
  coverContainer: {
    width: '100%',
    height: 140,
    backgroundColor: '#CBD5E1',
    position: 'relative',
  },
  editBlock: {
    position: 'absolute',
    right: 10,
    zIndex: 100,
    top: 10,
  },
  coverImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  card: {
    backgroundColor: '#fff',
    // borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 25,
    width: '100%',
    marginTop: 0, // overlap effect
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    // elevation: 4,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 15,
  },
  profileImageBlock: {
    position: 'relative',
  },
  editIcon: {
    position: 'absolute',
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 5,
    borderRadius: 25,
  },
  profileImage: {
    width: 90,
    height: 90,
    borderRadius: 50,
    marginTop: -60,
    borderWidth: 3,
    borderColor: '#fff',
  },
  name: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginTop: 8,
  },
  email: {
    color: '#1C9CDB',
    fontSize: 13,
    marginTop: 4,
  },
  infoContainer: {
    // borderTopWidth: 1,
    // borderColor: '#E5E7EB',
    marginTop: 5,
    paddingTop: 5,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  label: {
    color: '#6B7280',
    fontSize: 14,
  },
  value: {
    color: '#111827',
    fontWeight: '500',
    fontSize: 14,
  },
  link: {
    color: '#1C9CDB',
  },
  logoutButton: {
    marginTop: 25,
    backgroundColor: '#1C9CDB',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  logoutText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  separator: {
    height: 1,
    backgroundColor: '#D1D5DB',
    opacity: 0.6,
    marginVertical: 9,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 50,
    marginTop: -60,
    borderWidth: 3,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 32,
  },
  iconGeneralCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E6F0FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  heading: { fontSize: 18, fontWeight: '700', marginBottom: 10, marginTop: 8 },
  subheading: { color: '#666', marginBottom: 16 },
  submitBtn: {
    backgroundColor: '#0E79B6',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  coverPreviewWrapper: {
    position: 'relative',
    marginTop: 0,
    alignSelf: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    width: '100%',
    height: 140,
  },
  coverPreview: {
    width: '100%',
    height: 140,
    borderRadius: 8,
  },
  deleteButton: {
    position: 'absolute',
    top: '35%',
    left: '42%',
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 10,
    borderRadius: 25,
  },
  uploadPlaceholder: {
    borderWidth: 2,
    borderColor: '#93C5FD',
    borderStyle: 'dashed', // dashed border
    borderRadius: 10,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EFF6FF',
  },
  uploadIconWrapper: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  uploadText: {
    color: '#0E79B6',
    fontSize: 14,
    fontWeight: '600',
  },
});
